### ISSUE TITLE
authenticity_token_error

### ISSUE THREAD

**Issue by MASantangelo** [spatie/laravel-dashboard-twitter-tile#3]
Hello all,

Thanks for all the great work you've put into this dashboard!  I'm really loving it so far.

I'm encountering a slight problem when trying to use the twitter listener.  Specifically: 

msantangelo@Learning-Laravel:/var/www/laravel/dashboard$ php artisan dashboard:listen-twitter-mentions
Listening for mentions for configuration named `default`...

   Spatie\TwitterLabs\Exceptions\OauthException

  OAuth error. Are the client ID and client secret correct? Twitter API returned the following response:
{
    "errors": [
        {
            "code": 99,
            "message": "Unable to verify your credentials",
            "label": "authenticity_token_error"
        }
    ]
}

  at vendor/spatie/twitter-labs/src/Exceptions/OauthException.php:22
    18|         if (is_array($responseBody)) {
    19|             $responseBody = json_encode($responseBody, JSON_PRETTY_PRINT);
    20|         }
    21|
  > 22|         return new self($responseBody);
    23|     }
    24| }
    25|

      +21 vendor frames
  22  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

I went through and saw that someone else had an issue with their account not being linked to labs so I went ahead and linked it, and registered for FilteredStream

![image](https://user-images.githubusercontent.com/11986051/81003640-2be55d80-8e19-11ea-83f9-3b0e1cb73d28.png)

I even went as far as to regenerate my consumer_key and consumer_secret, but no matter what I do I cannot get it to listen.  

Any suggestions?

**Comment by MASantangelo** [comment]
As an update: I have used both curl and POST testing tools to confirm that I can get a valid bearer token for oauth2, I just can't trace the error anymore once it gets to guzzlehttp and promise. I'm not sure where the error is getting introduced in anymore.

msantangelo@Learning-Laravel:/var/www/laravel/dashboard$ curl -u 'TWITTER_CONSUMER_KEY:TWITTER_CONSUMER_SECRET' --data 'grant_type=client_credentials' 'https://api.twitter.com/oauth2/token'
{"token_type":"bearer","access_token":"A_VALID_TOKEN"}

**Comment by bandgeekndb** [comment]
@AlexVanderbist I think I found the source of the error for this. Sorry I don't have the chance to make a proper PR for it, but I'm hoping it's easy enough for you to test and verify.

In the ListenForMentionsCommand.php file: https://github.com/spatie/laravel-dashboard-twitter-tile/blob/6972b9d7fcf32454215f1120cef07ddaee4e696b/src/Commands/ListenForMentionsCommand.php#L29-L34, you initiate a FilterStreamFactory with the Access Token and Access Token Secret. This didn't feel right to me, I would have thought we would use the Consumer Key and Consumer Secret, just based on what little OAuth I've worked with.

I replaced the affected lines with the following and the command then worked as expected:

```
$filteredStream = FilteredStreamFactory::create(
    $configuration['consumer_key'],
    $configuration['consumer_secret'],
);
```

@MASantangelo you may want to try this in your own app and see if this works for you as well so it's not just my testing alone on this.

**Comment by MASantangelo** [comment]
@bandgeekndb Can confirm, dashboard listen commands worked after making this change, and the dashboard itself started to show tweets.

Set commands as part of Supervisor and now things are working fine.
![image](https://user-images.githubusercontent.com/11986051/81488938-d0163c80-923d-11ea-8d87-8e3884bbd6ae.png)
