### ISSUE TITLE
twitter tile throws an InvalidArgumentException error after running for a few minutes

### ISSUE THREAD

**Issue by darrenhusa** [spatie/laravel-dashboard-twitter-tile#6]
I am getting an error with the twitter dashboard tile after the dashboard runs for a few minutes.  The error is:

InvalidArgumentException
Malformed UTF-8 characters, possibly incorrectly encoded
http://<MY-LARAVEL-PROJECT>/livewire/message/twitter-tile 

Illuminate\Http\JsonResponse::setData
vendor/laravel/framework/src/Illuminate/Http/JsonResponse.php:75

I am using Laravel 7/php 7.4.8/MySQL 5.7 on macOS Catalina.

**Comment by safedrivepod** [comment]
Did you manage to fix this? I am having the same issue..

**Comment by AlexVanderbist** [comment]
Even we are having the same issue, lol. Seems that Livewire is doing something weird with the update payload. After refreshing the component renders the new tweets without issues.

**Comment by 1234abhishekjoshi** [comment]
Any solution for above issue
